{
    "family": "fargate-ecommerce-orders",
    "networkMode": "awsvpc",
    "containerDefinitions": [
        {
            "name": "orders",
            "image": "247523262683.dkr.ecr.us-east-1.amazonaws.com/fargate-ecommerce-orders:latest",
            "essential": true,
            "portMappings": [
                {
                    "containerPort": 8000,
                    "protocol": "tcp"
                }
            ],
            "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                    "awslogs-group": "/ecs/fargate-ecommerce-orders",
                    "awslogs-region": "us-east-1",
                    "awslogs-stream-prefix": "ecs"
                }
            }
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "cpu": "256",
    "memory": "512",
    "executionRoleArn": "arn:aws:iam::247523262683:role/ecsTaskExecutionRole"
}
